import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.menu': 'Menu',
    'nav.about': 'About Us',
    'nav.visit': 'Visit Us',
    'btn.reserve': 'Reserve a Table',
    'btn.order': 'Order Online',
    'hero.eyebrow': 'Artisanal Coffee · Kolkata',
    'hero.title': 'Slow Coffee, \nWarm Light, \nand a Seat That Feels Like Yours.',
    'hero.desc': 'A small and intimate retreat in Lake Gardens. Discover your favorite corner for solo work sessions or casual meetups.',
    'hero.viewMenu': 'View Menu',
    'hero.location': 'Located in Lake Gardens',
    'hero.featured': 'Featured Today',
    'hero.turmeric': 'The Turmeric Latte',
    'hero.turmericDesc': 'An earthy, golden blend that captures the warmth of a Kolkata morning.',
    'hero.signature': 'Signature Dish',
    'hero.diavolo': 'Diavolo Chicken Pizza',
    'hero.diavoloDesc': 'Spiced to perfection. Recommended by 120+ guests this month.',
    'features.handcrafted': 'Handcrafted Coffee',
    'features.handcraftedDesc': 'Brewing specialty beans with precision and care.',
    'features.ambience': 'Cozy Low-lit Ambience',
    'features.ambienceDesc': 'Soothing music and warm lighting for the perfect vibe.',
    'features.locals': 'Loved by Locals',
    'features.localsDesc': 'A popular neighborhood spot for conversations.',
    'features.rating': '4.3 Rating',
    'features.reviews': '(333 reviews)',
    'features.dineIn': 'Dine-in',
    'features.driveThrough': 'Drive-through',
    'features.delivery': 'No-contact Delivery',
    'features.lgbtq': 'LGBTQ+ friendly',
    'features.womenOwned': 'Women-owned',
    'menu.eyebrow': 'Our Offerings',
    'menu.title': 'The Menu',
    'menu.food': 'Food',
    'menu.beverages': 'Beverages',
    'menu.desserts': 'Desserts',
    'menu.veg': 'Vegetarian',
    'menu.nonveg': 'Non-Vegetarian',
    'menu.dietary': 'Dietary:',
    'menu.types': 'Types:',
    'menu.noItems': 'No items match your selected filters.',
    'menu.craving': 'Craving something from the menu?',
    'menu.cravingDesc': 'Join us at the cafe or get it delivered to your door.',
    'about.eyebrow': 'Our Story',
    'about.title': 'A Café Built for Slowing Down',
    'about.p1': 'CoLab is an artisanal coffee café in Lake Gardens, Kolkata, designed as a calm, low-lit retreat for people who want to work, meet, or simply unwind over a well-made cup of coffee.',
    'about.p2': 'Known locally for its soothing ambient music, intimate indoor and outdoor seating, and a menu that blends comfort food with specialty coffee craft, we strive to be your favorite neighborhood escape.',
    'about.reviews': 'Happy Reviews',
    'about.openLate': 'Open Late Daily',
    'about.quote': '"Guests love the soothing music and welcoming atmosphere. The perfect spot to read a book or catch up."',
    'visit.title': 'Find Your Seat at CoLab',
    'visit.desc': "We're located in the heart of Lake Gardens. Drop by for a coffee, stay for the vibe.",
    'visit.location': 'Location',
    'visit.address1': '164, 9/1, Prince Anwar Shah Road,',
    'visit.address2': 'Jodhpur Gardens, Lake Gardens,',
    'visit.address3': 'Kolkata, West Bengal 700045',
    'visit.hours': 'Hours',
    'visit.openDaily': 'Open Daily',
    'visit.contact': 'Contact',
    'visit.callUs': 'Call us for large bookings or inquiries.',
    'visit.directions': 'Get Directions',
    'insta.title': 'Follow the Story',
    'insta.follow': 'Follow Us',
    'footer.loyalty': 'Loyalty Rewards',
    'footer.join': 'Join the CoLab Club',
    'footer.joinDesc': 'Earn points on every coffee and pastry. Reach 100 points to unlock a free signature beverage or dessert. Enter your phone number to start earning today.',
    'footer.welcome': 'Welcome to the club! You\'re ready to earn points.',
    'footer.phone': 'Enter Phone Number',
    'footer.signup': 'Sign Up',
    'footer.desc': 'An artisanal coffee café designed as a calm, low-lit retreat for people who want to work, meet, or simply unwind.',
    'footer.visitHeader': 'Visit Us',
    'footer.hoursHeader': 'Hours & Info',
    'footer.hoursDesc': 'Open Daily: 10:30 AM – 10:00 PM',
    'footer.options': 'Dine-in · Drive-through · No-contact delivery',
    'footer.rights': 'CoLab Coffee Calcutta. All rights reserved.',
    'reserve.title': 'Reserve a Table',
    'reserve.name': 'Full Name',
    'reserve.phone': 'Phone Number',
    'reserve.date': 'Date',
    'reserve.time': 'Time',
    'reserve.noSlots': 'No slots',
    'reserve.noSlotsToday': 'No more reservation slots available today — please choose another date or call us at 089107 80424.',
    'reserve.confirming': 'Confirming your table...',
    'reserve.confirm': 'Confirm Reservation',
    'reserve.booked': "You're booked!",
    'reserve.ref': 'Booking Reference',
    'reserve.save': 'Please save this reference number for your visit.',
    'reserve.done': 'Done',
    'reserve.errorMsg': "We couldn't confirm your reservation right now. Please try again, or call us directly at 089107 80424.",
    'reserve.cancel': 'Cancel',
    'reserve.tryAgain': 'Try Again',
    'reserve.errorName': 'Please enter a valid name (letters only).',
    'reserve.errorPhone': 'Please enter a valid 10-digit Indian phone number.',
    'reserve.errorDate': 'Date is required.',
    'reserve.errorTime': 'Time is required.',
    'order.title': 'Order Online',
    'order.desc': 'Order CoLab from your favorite delivery partner',
    'order.zomato': 'Order on Zomato',
    'order.swiggy': 'Order on Swiggy',
    'order.opening': 'Opening...',
    'order.blocked': 'Pop-up blocked —',
    'order.manual': 'tap here to open manually',
    'order.phone': 'Prefer to order by phone?',
  },
  bn: {
    'nav.home': 'হোম',
    'nav.menu': 'মেনু',
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.visit': 'যোগাযোগ',
    'btn.reserve': 'টেবিল বুক করুন',
    'btn.order': 'অনলাইনে অর্ডার করুন',
    'hero.eyebrow': 'আর্টিজানাল কফি · কলকাতা',
    'hero.title': 'ধীর কফি, \nউষ্ণ আলো, \nএবং আপনার নিজের মতো একটি আসন।',
    'hero.desc': 'লেক গার্ডেন্সে একটি ছোট এবং অন্তরঙ্গ আশ্রয়। একাকী কাজের জন্য বা আড্ডার জন্য আপনার প্রিয় কোণটি আবিষ্কার করুন।',
    'hero.viewMenu': 'মেনু দেখুন',
    'hero.location': 'লেক গার্ডেন্সে অবস্থিত',
    'hero.featured': 'আজকের বিশেষ',
    'hero.turmeric': 'দ্য টারমারিক লাটে',
    'hero.turmericDesc': 'একটি মাটির, সোনালী মিশ্রণ যা কলকাতার সকালের উষ্ণতা ধারণ করে।',
    'hero.signature': 'সিগনেচার ডিশ',
    'hero.diavolo': 'ডায়াভোলো চিকেন পিজ্জা',
    'hero.diavoloDesc': 'নিখুঁত মশলাদার। এই মাসে ১২০+ অতিথিদের দ্বারা প্রস্তাবিত।',
    'features.handcrafted': 'হাতে তৈরি কফি',
    'features.handcraftedDesc': 'সতর্কতা এবং নির্ভুলতার সাথে স্পেশালিটি বিন ব্রিউ করা হয়।',
    'features.ambience': 'আরামদায়ক স্বল্প-আলোকিত পরিবেশ',
    'features.ambienceDesc': 'নিখুঁত অনুভূতির জন্য প্রশান্তিদায়ক সঙ্গীত এবং উষ্ণ আলো।',
    'features.locals': 'স্থানীয়দের প্রিয়',
    'features.localsDesc': 'কথোপকথনের জন্য একটি জনপ্রিয় পাড়ার জায়গা।',
    'features.rating': '৪.৩ রেটিং',
    'features.reviews': '(৩৩৩ রিভিউ)',
    'features.dineIn': 'ডাইন-ইন',
    'features.driveThrough': 'ড্রাইভ-থ্রু',
    'features.delivery': 'যোগাযোগহীন ডেলিভারি',
    'features.lgbtq': 'LGBTQ+ বন্ধুত্বপূর্ণ',
    'features.womenOwned': 'নারীদের দ্বারা পরিচালিত',
    'menu.eyebrow': 'আমাদের পরিবেশনা',
    'menu.title': 'মেনু',
    'menu.food': 'খাবার',
    'menu.beverages': 'পানীয়',
    'menu.desserts': 'ডেজার্ট',
    'menu.veg': 'নিরামিষ',
    'menu.nonveg': 'আমিষ',
    'menu.dietary': 'খাদ্যবিধি:',
    'menu.types': 'প্রকার:',
    'menu.noItems': 'আপনার নির্বাচিত ফিল্টারের সাথে কোনো আইটেম মেলে না।',
    'menu.craving': 'মেনু থেকে কিছু খেতে ইচ্ছে করছে?',
    'menu.cravingDesc': 'ক্যাফেতে আমাদের সাথে যোগ দিন বা আপনার দরজায় ডেলিভারি পান।',
    'about.eyebrow': 'আমাদের গল্প',
    'about.title': 'ধীর গতির জন্য নির্মিত একটি ক্যাফে',
    'about.p1': 'কোলাব হল কলকাতার লেক গার্ডেন্সে একটি আর্টিজানাল কফি ক্যাফে, যা এমন লোকেদের জন্য একটি শান্ত, স্বল্প-আলোকিত আশ্রয় হিসেবে ডিজাইন করা হয়েছে যারা কাজ করতে, দেখা করতে বা এক কাপ ভালো কফির সাথে বিশ্রাম নিতে চান।',
    'about.p2': 'এর প্রশান্তিদায়ক পরিবেষ্টিত সঙ্গীত, অন্তরঙ্গ ইনডোর এবং আউটডোর বসার জায়গা এবং একটি মেনু যা আরামদায়ক খাবারের সাথে বিশেষ কফি নৈপুণ্যের মিশ্রণ ঘটায়, তার জন্য স্থানীয়ভাবে পরিচিত, আমরা আপনার প্রিয় পাড়ার পালানোর জায়গা হওয়ার চেষ্টা করি।',
    'about.reviews': 'খুশি রিভিউ',
    'about.openLate': 'প্রতিদিন গভীর রাত পর্যন্ত খোলা',
    'about.quote': '"অতিথিরা প্রশান্তিদায়ক সঙ্গীত এবং স্বাগত জানানোর পরিবেশ পছন্দ করেন। বই পড়ার বা আড্ডা দেওয়ার জন্য উপযুক্ত জায়গা।"',
    'visit.title': 'কোলাব এ আপনার আসন খুঁজুন',
    'visit.desc': 'আমরা লেক গার্ডেন্সের হৃদয়ে অবস্থিত। কফির জন্য আসুন, অনুভূতির জন্য থাকুন।',
    'visit.location': 'অবস্থান',
    'visit.address1': '১৬৪, ৯/১, প্রিন্স আনোয়ার শাহ রোড,',
    'visit.address2': 'যোধপুর গার্ডেন্স, লেক গার্ডেন্স,',
    'visit.address3': 'কলকাতা, পশ্চিমবঙ্গ ৭০০০৪৫',
    'visit.hours': 'সময়',
    'visit.openDaily': 'প্রতিদিন খোলা',
    'visit.contact': 'যোগাযোগ',
    'visit.callUs': 'বড় বুকিং বা জিজ্ঞাসাবাদের জন্য আমাদের কল করুন।',
    'visit.directions': 'দিকনির্দেশ পান',
    'insta.title': 'গল্পটি অনুসরণ করুন',
    'insta.follow': 'আমাদের অনুসরণ করুন',
    'footer.loyalty': 'লয়ালটি রিওয়ার্ডস',
    'footer.join': 'কোলাব ক্লাবে যোগ দিন',
    'footer.joinDesc': 'প্রতিটি কফি এবং পেস্ট্রিতে পয়েন্ট অর্জন করুন। একটি বিনামূল্যে সিগনেচার পানীয় বা ডেজার্ট আনলক করতে ১০০ পয়েন্টে পৌঁছান। আজই উপার্জন শুরু করতে আপনার ফোন নম্বর লিখুন।',
    'footer.welcome': 'ক্লাবে স্বাগতম! আপনি পয়েন্ট অর্জন করতে প্রস্তুত।',
    'footer.phone': 'ফোন নম্বর লিখুন',
    'footer.signup': 'সাইন আপ করুন',
    'footer.desc': 'একটি শান্ত, স্বল্প-আলোকিত আশ্রয় হিসেবে ডিজাইন করা একটি আর্টিজানাল কফি ক্যাফে, এমন লোকেদের জন্য যারা কাজ করতে, দেখা করতে বা কেবল বিশ্রাম নিতে চান।',
    'footer.visitHeader': 'আমাদের ভিজিট করুন',
    'footer.hoursHeader': 'সময় এবং তথ্য',
    'footer.hoursDesc': 'প্রতিদিন খোলা: সকাল ১০:৩০ – রাত ১০:০০',
    'footer.options': 'ডাইন-ইন · ড্রাইভ-থ্রু · যোগাযোগহীন ডেলিভারি',
    'footer.rights': 'কোলাব কফি কলকাতা। সর্বস্বত্ব সংরক্ষিত।',
    'reserve.title': 'টেবিল বুক করুন',
    'reserve.name': 'পুরো নাম',
    'reserve.phone': 'ফোন নম্বর',
    'reserve.date': 'তারিখ',
    'reserve.time': 'সময়',
    'reserve.noSlots': 'কোন স্লট নেই',
    'reserve.noSlotsToday': 'আজ কোনো রিজার্ভেশন স্লট উপলব্ধ নেই — অনুগ্রহ করে অন্য তারিখ বেছে নিন বা আমাদের ০৮৯১০৭ ৮০৪২৪ নম্বরে কল করুন।',
    'reserve.confirming': 'আপনার টেবিল নিশ্চিত করা হচ্ছে...',
    'reserve.confirm': 'রিজার্ভেশন নিশ্চিত করুন',
    'reserve.booked': "আপনার বুকিং সম্পন্ন হয়েছে!",
    'reserve.ref': 'বুকিং রেফারেন্স',
    'reserve.save': 'আপনার দর্শনের জন্য দয়া করে এই রেফারেন্স নম্বরটি সংরক্ষণ করুন।',
    'reserve.done': 'সম্পন্ন',
    'reserve.errorMsg': "আমরা এই মুহূর্তে আপনার রিজার্ভেশন নিশ্চিত করতে পারিনি। অনুগ্রহ করে আবার চেষ্টা করুন, অথবা সরাসরি ০৮৯১০৭ ৮০৪২৪ নম্বরে আমাদের কল করুন।",
    'reserve.cancel': 'বাতিল করুন',
    'reserve.tryAgain': 'আবার চেষ্টা করুন',
    'reserve.errorName': 'অনুগ্রহ করে একটি বৈধ নাম লিখুন (শুধুমাত্র অক্ষর)।',
    'reserve.errorPhone': 'অনুগ্রহ করে একটি বৈধ ১০-সংখ্যার ভারতীয় ফোন নম্বর লিখুন।',
    'reserve.errorDate': 'তারিখ আবশ্যক।',
    'reserve.errorTime': 'সময় আবশ্যক।',
    'order.title': 'অনলাইনে অর্ডার করুন',
    'order.desc': 'আপনার প্রিয় ডেলিভারি পার্টনার থেকে কোলাব অর্ডার করুন',
    'order.zomato': 'Zomato তে অর্ডার করুন',
    'order.swiggy': 'Swiggy তে অর্ডার করুন',
    'order.opening': 'খোলা হচ্ছে...',
    'order.blocked': 'পপ-আপ ব্লক করা হয়েছে —',
    'order.manual': 'ম্যানুয়ালি খুলতে এখানে ট্যাপ করুন',
    'order.phone': 'ফোনে অর্ডার করতে পছন্দ করেন?',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'bn' : 'en');
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
